const ProgressActionTypes = {
  CURRENT_ROUTER: 'CURRENT_ROUTER',
  NEXT_QUESTION: 'NEXT_QUESTION',
  TOTAL_QUESTIONS: 'TOTAL_QUESTIONS',
  CURRENT_ANSWER: 'CURRENT_ANSWER',
  SCORE: 'SCORE',
  RESET_DATA: 'RESET_DATA'
};

export default ProgressActionTypes
